### ISSUE TITLE
Bogus "bad --isa option"

### ISSUE THREAD

**Issue by scottj97** [riscv-software-src/riscv-isa-sim#361] opened 2019-11-25 03:34 UTC
In change 0162a6e72421b5cbec1905b4cae7bfab98afe83f, `parse_isa_string()` changed so it sets only `max_isa` and not `state.misa`. But at the end of that function, it calls `supports_extension()` which checks `state.misa`, which is uninitialized, leading to random bogus failures such as:

```
error: bad --isa option RV64IMAC
```

**Comment by aswaterman** [comment] 2019-11-25 05:04
Thanks for the bug report.  The problem is that `state.misa` just isn't initialized at that point, so the behavior is undefined.  As luck would have it, it always happens to get zero-initialized in my use cases, so I can't see the bug without forcibly initializing the memory to some other value.

**Comment by aswaterman** [comment] 2019-11-25 05:22
I marked this as closed in the referenced commit, but please reopen if it doesn't fix your use case.

**Closed as completed** 2019-11-25 05:22 UTC

**Comment by scottj97** [comment] 2019-11-25 14:33
Works great, thank you!
